server:
  port: 8080
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: FLIGHT-SERVICE
          uri: lb://FLIGHT-SERVICE
          predicates:
            - Path=/api/v1/flight/**
            - Path=/api/v1/scheduled-flight/**
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order/**
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**
        - id: REDIS-SERVICE
          uri: lb://REDIS-SERVICE
          predicates:
            - Path=/api/v1/cache/**
  data:
    mongodb:
      database: flight
